"""choices added to survey and answer text removed

Revision ID: 1459221e4276
Revises: 957dca919d79
Create Date: 2025-05-14 19:37:10.978177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1459221e4276'
down_revision = '957dca919d79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.drop_column('answer_text')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('answer_text', sa.TEXT(), nullable=False))

    # ### end Alembic commands ###
