"""Change Choice.surveys to many-to-many relationship

Revision ID: 8a0b8e034fdb
Revises: eeead2cbb048
Create Date: 2025-06-07 21:28:31.545841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a0b8e034fdb'
down_revision = 'eeead2cbb048'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('survey_choices',
    sa.Column('survey_id', sa.Integer(), nullable=False),
    sa.Column('choice_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['choice_id'], ['choice.id'], ),
    sa.ForeignKeyConstraint(['survey_id'], ['survey.id'], ),
    sa.PrimaryKeyConstraint('survey_id', 'choice_id')
    )
    with op.batch_alter_table('choice', schema=None) as batch_op:
        batch_op.drop_constraint('fk_choice_surveys_on_survey_id', type_='foreignkey')
        batch_op.drop_column('surveys')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('choice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('surveys', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_choice_surveys_on_survey_id', 'survey', ['surveys'], ['id'])

    op.drop_table('survey_choices')
    # ### end Alembic commands ###
