"""fixed many to many relation

Revision ID: eeead2cbb048
Revises: 1459221e4276
Create Date: 2025-05-14 20:13:08.818990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eeead2cbb048'
down_revision = '1459221e4276'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('choice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('surveys', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_choice_surveys_on_survey_id', 'survey', ['surveys'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('choice', schema=None) as batch_op:
        batch_op.drop_constraint('fk_choice_surveys_on_survey_id', type_='foreignkey')
        batch_op.drop_column('surveys')

    # ### end Alembic commands ###
